In [2]:
import numpy as np

In [3]:
A = np.full((10,15),1,dtype=np.float32)

In [13]:
B = np.full((1,15),(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15),dtype=np.uint8)

In [14]:
C = A*B

In [15]:
C.shape

(10, 15)

In [16]:
C.dtype

dtype('float32')

In [17]:
C.astype(np.uint8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]],
      dtype=uint8)

In [18]:
C[C < 7]

array([1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5.,
       6., 1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5., 6., 1., 2., 3., 4.,
       5., 6., 1., 2., 3., 4., 5., 6., 1., 2., 3., 4., 5., 6., 1., 2., 3.,
       4., 5., 6., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [19]:
C[C < 7] = 7

In [67]:
C.shape

(10, 15)

In [68]:
D = np.diag(B)

In [69]:
E = D + C

In [70]:
F = C.mean(axis=0)

In [71]:
G = C + F

In [72]:
G

array([[14., 14., 14., 14., 14., 14., 14., 16., 18., 20., 22., 24., 26.,
        28., 30.],
       [14., 14., 14., 14., 14., 14., 14., 16., 18., 20., 22., 24., 26.,
        28., 30.],
       [14., 14., 14., 14., 14., 14., 14., 16., 18., 20., 22., 24., 26.,
        28., 30.],
       [14., 14., 14., 14., 14., 14., 14., 16., 18., 20., 22., 24., 26.,
        28., 30.],
       [14., 14., 14., 14., 14., 14., 14., 16., 18., 20., 22., 24., 26.,
        28., 30.],
       [14., 14., 14., 14., 14., 14., 14., 16., 18., 20., 22., 24., 26.,
        28., 30.],
       [14., 14., 14., 14., 14., 14., 14., 16., 18., 20., 22., 24., 26.,
        28., 30.],
       [14., 14., 14., 14., 14., 14., 14., 16., 18., 20., 22., 24., 26.,
        28., 30.],
       [14., 14., 14., 14., 14., 14., 14., 16., 18., 20., 22., 24., 26.,
        28., 30.],
       [14., 14., 14., 14., 14., 14., 14., 16., 18., 20., 22., 24., 26.,
        28., 30.]], dtype=float32)

In [73]:
G.shape

(10, 15)